[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  base = "frontend"
  command = "bash netlify-build.sh"
  publish = "dist"

[context.production.environment]
  VITE_BACKEND_URL = "https://chatty-app-gamma.vercel.app"
  VITE_SOCKET_URL = "https://chatty-app-gamma.vercel.app"
  VITE_PORT = "5173"
