[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_BACKEND_URL = "https://your-backend-url.herokuapp.com"
  VITE_SOCKET_URL = "https://your-backend-url.herokuapp.com"
