name = "chatty-frontend"
type = "webpack"
account_id = ""  # Your Cloudflare account ID
workers_dev = true

[site]
bucket = "./dist"  # Your build output directory
entry-point = "workers-site"

[env.production]
name = "chatty-frontend-prod"
route = "your-domain.com/*"  # Replace with your domain

[env.production.vars]
VITE_BACKEND_URL = "wss://your-backend-url.workers.dev"  # Replace with your backend URL
