services:
  - type: web
    name: chatty-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: chatty-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: chatty-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8000
    healthCheckPath: /api/health

databases:
  - name: chatty-db
    plan: free
    ipAllowList: []  # Restrict as needed
