name = "chatty-backend"
main = "src/worker.js"
compatibility_date = "2024-01-19"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
MONGODB_URI = ""  # You'll need to set this in Cloudflare's dashboard
JWT_SECRET = ""   # You'll need to set this in Cloudflare's dashboard

[build]
command = "npm install"
watch_dir = "src"

[triggers]
crons = ["*/5 * * * *"]  # Run every 5 minutes to keep the worker alive

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[durable_objects]
bindings = []

[[migrations]]
tag = "v1"
new_classes = []
