name = "chatty-backend"
main = "src/app.js"
compatibility_date = "2024-01-19"

[vars]
MONGODB_URI = ""  # You'll need to set this in Cloudflare's dashboard
JWT_SECRET = ""   # You'll need to set this in Cloudflare's dashboard

[[routes]]
pattern = "/api/*"
zone_name = "your-domain.com"
