name = "chatty-backend"
compatibility_date = "2024-01-19"
compatibility_flags = ["nodejs_compat"]

[vars]
MONGODB_URI = ""  # You'll need to set this in Cloudflare's dashboard
JWT_SECRET = ""   # You'll need to set this in Cloudflare's dashboard

[site]
bucket = "./public"  # Static assets directory

[triggers]
crons = ["*/5 * * * *"]  # Run every 5 minutes to keep the worker alive
